openapi: 3.0.3
info:
  title: Accounts API
  description: API for managing user accounts, balances, and onboarding workflows
  version: 1.0.0

servers:
  - url: http://localhost:3002
    description: Local development server

paths:
  /accounts:
    post:
      summary: Create Account
      description: Creates an account for an existing user
      operationId: createAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
      responses:
        '201':
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '400':
          description: Bad request - userId is required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: List Accounts
      description: Lists accounts for a user
      operationId: listAccounts
      parameters:
        - name: userId
          in: query
          required: true
          description: The user ID to filter accounts by
          schema:
            type: string
      responses:
        '200':
          description: List of accounts retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountListResponse'
        '400':
          description: Bad request - userId query is required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /accounts/{id}:
    get:
      summary: Get Account
      description: Fetches an account by id along with its balance
      operationId: getAccount
      parameters:
        - name: id
          in: path
          required: true
          description: The account ID
          schema:
            type: string
      responses:
        '200':
          description: Account retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountWithBalanceResponse'
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /accounts/{id}/credit:
    post:
      summary: Credit Account
      description: Applies a credit to an account balance
      operationId: creditAccount
      parameters:
        - name: id
          in: path
          required: true
          description: The account ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditRequest'
      responses:
        '200':
          description: Credit applied successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
        '400':
          description: Bad request - amount must be a number
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /accounts/onboard:
    post:
      summary: Onboard User
      description: Creates a user, creates an account, optionally credits it, and assigns a product via the catalog service
      operationId: onboardUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OnboardRequest'
      responses:
        '201':
          description: User onboarded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnboardResponse'
        '400':
          description: Bad request - name, email, and productId are required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /health:
    get:
      summary: Health Check
      description: Basic service health check
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
          description: Unique account identifier
        userId:
          type: string
          description: The user ID associated with this account
        type:
          type: string
          description: Account type
        createdAt:
          type: string
          format: date-time
          description: Account creation timestamp
      required:
        - id
        - userId
        - type
        - createdAt

    CreateAccountRequest:
      type: object
      properties:
        userId:
          type: string
          description: The user ID to create an account for
        type:
          type: string
          description: Account type
          default: standard
      required:
        - userId

    AccountResponse:
      type: object
      properties:
        account:
          $ref: '#/components/schemas/Account'

    AccountListResponse:
      type: object
      properties:
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/Account'

    AccountWithBalanceResponse:
      type: object
      properties:
        account:
          $ref: '#/components/schemas/Account'
        balance:
          type: number
          description: Current account balance

    CreditRequest:
      type: object
      properties:
        amount:
          type: number
          description: Amount to credit to the account
      required:
        - amount

    BalanceResponse:
      type: object
      properties:
        accountId:
          type: string
          description: The account ID
        balance:
          type: number
          description: Updated account balance

    OnboardRequest:
      type: object
      properties:
        name:
          type: string
          description: User's name
        email:
          type: string
          format: email
          description: User's email address
        productId:
          type: string
          description: Product ID to assign to the user
        initialCredit:
          type: number
          description: Initial credit amount
          default: 0
      required:
        - name
        - email
        - productId

    OnboardResponse:
      type: object
      properties:
        user:
          type: object
          description: Created user object
        account:
          $ref: '#/components/schemas/Account'
        assignment:
          type: object
          description: Product assignment object
        balance:
          type: number
          description: Account balance after initial credit

    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: ok
        service:
          type: string
          example: accounts-api

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
